version: '3.1'

services:
    php:
        build: ./
        ports:
            - "8081:9000"
        volumes:
            - ./:/app

    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./mysql:/var/lib/mysql
    
    myadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "3308:80"
